"""Create weekly_hours table

Revision ID: 163867c718b8
Revises: 47e2adc04e94
Create Date: 2025-03-16 18:15:20.323993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163867c718b8'
down_revision: Union[str, None] = '47e2adc04e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_hours',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.String(length=10), nullable=False),
    sa.Column('week_end', sa.String(length=10), nullable=False),
    sa.Column('scheduled_hours', sa.Float(), nullable=False),
    sa.Column('worked_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['User.id'], name='fk_weekly_hours_employee'),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], name='fk_weekly_hours_organization'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_hours')
    # ### end Alembic commands ###
