"""soft delete revision

Revision ID: 43aa9fa7359b
Revises: ce53b8b98220
Create Date: 2025-02-22 16:46:28.343861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aa9fa7359b'
down_revision: Union[str, None] = 'ce53b8b98220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmployeePunch', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Organization', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('OrganizationCategory', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('OrganizationSubscriptionPayment', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('OrganizationSubscriptionSettings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Payslip', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('Shift', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('SubscriptionPlan', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('User', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'deleted_at')
    op.drop_column('SubscriptionPlan', 'deleted_at')
    op.drop_column('Shift', 'deleted_at')
    op.drop_column('Payslip', 'deleted_at')
    op.drop_column('OrganizationSubscriptionSettings', 'deleted_at')
    op.drop_column('OrganizationSubscriptionPayment', 'deleted_at')
    op.drop_column('OrganizationCategory', 'deleted_at')
    op.drop_column('Organization', 'deleted_at')
    op.drop_column('EmployeePunch', 'deleted_at')
    # ### end Alembic commands ###
