"""add preset table

Revision ID: 47e2adc04e94
Revises: 8c4cc7365ab2
Create Date: 2025-03-05 12:56:19.312966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e2adc04e94'
down_revision: Union[str, None] = '8c4cc7365ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShiftPresetGroup',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('worksite_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], name='fk_shift_preset_grou_organization'),
    sa.ForeignKeyConstraint(['worksite_id'], ['WorkSite.id'], name='fk_shift_preset_group_worksite'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ShiftPreset', sa.Column('preset_group_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_shift_preset_worksite', 'ShiftPreset', type_='foreignkey')
    op.create_foreign_key('fk_shift_preset_preset_group', 'ShiftPreset', 'ShiftPresetGroup', ['preset_group_id'], ['id'])
    op.drop_column('ShiftPreset', 'worksite_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShiftPreset', sa.Column('worksite_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_shift_preset_preset_group', 'ShiftPreset', type_='foreignkey')
    op.create_foreign_key('fk_shift_preset_worksite', 'ShiftPreset', 'WorkSite', ['worksite_id'], ['id'])
    op.drop_column('ShiftPreset', 'preset_group_id')
    op.drop_table('ShiftPresetGroup')
    # ### end Alembic commands ###
