"""add inactive user

Revision ID: 546c3228c50d
Revises: 82ffd2343907
Create Date: 2025-03-24 12:33:06.469552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "546c3228c50d"
down_revision: Union[str, None] = "82ffd2343907"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "is_active")

    # ### end Alembic commands ###
