"""refact shift to string

Revision ID: 8278ee01d027
Revises: 43aa9fa7359b
Create Date: 2025-02-23 11:14:16.672281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8278ee01d027'
down_revision: Union[str, None] = '43aa9fa7359b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EmployeePunch', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('EmployeePunch', 'punch_in_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('EmployeePunch', 'punch_out_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               nullable=False)
    op.alter_column('Payslip', 'period_start',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('Payslip', 'period_end',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('Shift', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('Shift', 'shift_start',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('Shift', 'shift_end',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shift', 'shift_end',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('Shift', 'shift_start',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('Shift', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('Payslip', 'period_end',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('Payslip', 'period_start',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('EmployeePunch', 'punch_out_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               nullable=True)
    op.alter_column('EmployeePunch', 'punch_in_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('EmployeePunch', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
