"""add overtime hours in employee punch

Revision ID: 82ffd2343907
Revises: a15f0dcd735e
Create Date: 2025-03-23 13:16:05.280956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82ffd2343907"
down_revision: Union[str, None] = "a15f0dcd735e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "EmployeePunch", sa.Column("overtime_hours", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_employee_org_week",
        "weekly_hours",
        ["employee_id", "organization_id", "week_start"],
    )
    op.drop_column("EmployeePunch", "overtime_hours")
    # ### end Alembic commands ###
