"""add preset table

Revision ID: 8c4cc7365ab2
Revises: 117a3f6ce960
Create Date: 2025-02-27 11:08:55.616081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4cc7365ab2'
down_revision: Union[str, None] = '117a3f6ce960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ShiftPreset',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('worksite_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('shift_start', sa.String(length=5), nullable=False),
    sa.Column('shift_end', sa.String(length=5), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['User.id'], name='fk_shift_preset_employee'),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], name='fk_shift_preset_organization'),
    sa.ForeignKeyConstraint(['worksite_id'], ['WorkSite.id'], name='fk_shift_preset_worksite'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Shift', sa.Column('worksite_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_shift_worksite', 'Shift', 'WorkSite', ['worksite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shift_worksite', 'Shift', type_='foreignkey')
    op.drop_column('Shift', 'worksite_id')
    op.drop_table('ShiftPreset')
    # ### end Alembic commands ###
