"""Add is_deleted column to weekly_hours table

Revision ID: a15f0dcd735e
Revises: 163867c718b8
Create Date: 2025-03-16 20:46:09.034269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15f0dcd735e'
down_revision: Union[str, None] = '163867c718b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraint only if it exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    constraints = inspector.get_unique_constraints('weekly_hours')
    constraint_names = [c['name'] for c in constraints]
    
    if 'unique_employee_org_week' in constraint_names:
        op.drop_constraint('unique_employee_org_week', 'weekly_hours', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_org_week', 'weekly_hours', ['employee_id', 'organization_id', 'week_start'])
    # ### end Alembic commands ###
