"""add title 

Revision ID: e876cbdb05c0
Revises: 8278ee01d027
Create Date: 2025-02-23 11:26:35.767021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e876cbdb05c0'
down_revision: Union[str, None] = '8278ee01d027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shift', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shift', 'title')
    # ### end Alembic commands ###
