name: Dependency Updates

on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2 AM
  workflow_dispatch:

jobs:
  update-npm-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Update npm dependencies
        run: |
          npm update
          npm audit fix --force || true

      - name: Update web dependencies
        run: |
          cd apps/web
          npm update
          npm audit fix --force || true

      - name: Update app dependencies
        run: |
          cd apps/app
          npm update
          npm audit fix --force || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update npm dependencies"
          title: "chore: update npm dependencies"
          body: |
            Automated dependency updates:
            - Updated npm dependencies across all packages
            - Fixed security vulnerabilities where possible

            Please review the changes and test thoroughly before merging.
          branch: chore/update-npm-dependencies
          delete-branch: true

  update-python-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Update Python dependencies
        run: |
          cd apps/api
          uv lock --upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Python dependencies"
          title: "chore: update Python dependencies"
          body: |
            Automated Python dependency updates:
            - Updated uv.lock with latest compatible versions

            Please review the changes and test thoroughly before merging.
          branch: chore/update-python-dependencies
          delete-branch: true
